import os
import time
import shutil
from util import merge, remove, pprint
from functools import reduce
# third-party
import jinja2 as j2
import yaml
import fabric.api as fab
import fabric.contrib.console as console

templates = {
    'settings.php.j2': 'bitrix/.settings.php',
    'dbconn.php.j2': 'bitrix/php_interface/dbconn.php'
}


def config():
    defaults = {
        'generated_message': 'This file is generated by Fabric, all changes will be lost'
    }
    return reduce(merge, [
        dict(defaults),
        yaml.load(open('vars.yml')),
        yaml.load(open('vars/secrets.yml'))
    ])


def init():
    for role in cfg['roles']:
        if role != 'all':
            for host in cfg['roles'][role].get('hosts', []):
                # plug into fabric
                fab.env.roledefs.setdefault(role, []).append(host)


# global state

cfg = config()
templates_path = os.path.join(os.path.dirname(__file__), 'templates')
j2env = j2.Environment(loader=j2.FileSystemLoader(templates_path),
                       undefined=j2.StrictUndefined,
                       trim_blocks=True)
# fabric setup
init()


def environment(roles=None, host=None):
    if roles is None:
        roles = fab.env.roles
    if host is None:
        host = fab.env.host
    if not host:
        fab.warn('no host')
    role_configs = [cfg['roles'][role] for role in roles]
    global_vars = remove(cfg, ['roles', 'hosts'])
    return reduce(merge, [global_vars, cfg['hosts'][host] if host else [], cfg['roles']['all']] + role_configs)


def backup_filename(filename):
    return '{}.{}~'.format(filename, time.strftime('%Y-%m-%d@%H:%M:%S'))


# path relative to the document root
def write_file(env, path, contents, backup=True):
    # TODO implement remote/ftp
    assert env['local'] and env['document_root']
    abs_path = os.path.join(env['document_root'], path)
    if backup and os.path.exists(abs_path):
        [directory, filename] = os.path.split(abs_path)
        dest = os.path.join(directory, backup_filename(filename))
        shutil.copy(abs_path, dest)
        fab.puts('backup created: {}'.format(dest))
    console.confirm('write to {}?'.format(abs_path))
    with open(abs_path, 'w') as file:
        file.write(contents)


@fab.task
def print_env():
    pprint(environment())


@fab.task
def push_configs():
    env = environment()
    # TODO diff with existing and print
    for name, rel_path in templates.items():
        # TODO contents formatting is messed up right now
        contents = j2env.get_template(name).render(env)
        write_file(env, rel_path, contents)


@fab.task(alias='gitftp')
def git_ftp(args):
    ftp = environment()['ftp']
    git_ftp_args = ['--user', ftp['user'], '--passwd', ftp['password'], ftp['url']]
    fab.local('git-ftp {} {}'.format(args, ' '.join(git_ftp_args)))


@fab.task
def deploy():
    # TODO
    # maintenance mode on
    # push configs
    # push staging robots.txt
    # local composer install
    # local npm install
    # local build assets
    # sync directories: build, composer vendor, mockup
    # git-ftp push
    # clear bitrix cache
    # notify in slack
    # maintenance mode off
    pass
