roles:
  all:
    app_debug: false
    sentry:
      enabled: true
  dev:
    local: true
    app_env: dev
    app_debug: true
    hosts: [local]
    sentry:
      enabled: false
  stage:
    app_env: prod
    app_debug: true
    hosts: [imarket]
