<?
use Bex\Tools\Iblock\IblockTools;
use App\Iblock;

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Аналитика, экспертные мнения");
$APPLICATION->SetPageProperty('layout', 'bare');
?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"opinions", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "DETAIL_TEXT",
			2 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			/*текстовые блоки (от 1 - т.к. превый (нулевой) текстовый блоке берётся из DETAIL_TEXT)*/
            1 => "TEXT_BLOCK_1",
            2 => "TEXT_BLOCK_2",
            3 => "TEXT_BLOCK_3",
            4 => "TEXT_BLOCK_4",
            5 => "TEXT_BLOCK_5",
            6 => "TEXT_BLOCK_6",
            7 => "TEXT_BLOCK_7",
            8 => "TEXT_BLOCK_8",
            9 => "TEXT_BLOCK_9",
            10 => "TEXT_BLOCK_10",
            11 => "TEXT_BLOCK_11",
            12 => "TEXT_BLOCK_12",
            13 => "TEXT_BLOCK_13",
            14 => "TEXT_BLOCK_14",
            15 => "TEXT_BLOCK_15",
            16 => "TEXT_BLOCK_16",
            17 => "TEXT_BLOCK_17",
            18 => "TEXT_BLOCK_18",
            19 => "TEXT_BLOCK_19",
			/*блоки изображений*/
			20 => "IMG_BLOCK_0",
			21 => "IMG_BLOCK_1",
			22 => "IMG_BLOCK_2",
			23 => "IMG_BLOCK_3",
			24 => "IMG_BLOCK_4",
			25 => "IMG_BLOCK_5",
			26 => "IMG_BLOCK_6",
			27 => "IMG_BLOCK_7",
			28 => "IMG_BLOCK_8",
			29 => "IMG_BLOCK_9",
			30 => "IMG_BLOCK_10",
			31 => "IMG_BLOCK_11",
			32 => "IMG_BLOCK_12",
			33 => "IMG_BLOCK_13",
			34 => "IMG_BLOCK_14",
			35 => "IMG_BLOCK_15",
			36 => "IMG_BLOCK_16",
			37 => "IMG_BLOCK_17",
			38 => "IMG_BLOCK_18",
			39 => "IMG_BLOCK_19",
			/*Блок со звездой - описания */
			40 => "STAR_BLOCK_DESCR_0",
			41 => "STAR_BLOCK_DESCR_1",
			42 => "STAR_BLOCK_DESCR_2",
			43 => "STAR_BLOCK_DESCR_3",
			44 => "STAR_BLOCK_DESCR_4",
			45 => "STAR_BLOCK_DESCR_5",
			46 => "STAR_BLOCK_DESCR_6",
			47 => "STAR_BLOCK_DESCR_7",
			48 => "STAR_BLOCK_DESCR_8",
			49 => "STAR_BLOCK_DESCR_9",
			50 => "STAR_BLOCK_DESCR_10",
			51 => "STAR_BLOCK_DESCR_11",
			52 => "STAR_BLOCK_DESCR_12",
			53 => "STAR_BLOCK_DESCR_13",
			54 => "STAR_BLOCK_DESCR_14",
			55 => "STAR_BLOCK_DESCR_15",
			56 => "STAR_BLOCK_DESCR_16",
			57 => "STAR_BLOCK_DESCR_17",
			58 => "STAR_BLOCK_DESCR_18",
			59 => "STAR_BLOCK_DESCR_19",
            /*Блок со звездой - ссылки */
            60 => "STAR_BLOCK_LINK_0",
            61 => "STAR_BLOCK_LINK_1",
            62 => "STAR_BLOCK_LINK_2",
            63 => "STAR_BLOCK_LINK_3",
            64 => "STAR_BLOCK_LINK_4",
            65 => "STAR_BLOCK_LINK_5",
            66 => "STAR_BLOCK_LINK_6",
            67 => "STAR_BLOCK_LINK_7",
            68 => "STAR_BLOCK_LINK_8",
            69 => "STAR_BLOCK_LINK_9",
            70 => "STAR_BLOCK_LINK_10",
            71 => "STAR_BLOCK_LINK_11",
            72 => "STAR_BLOCK_LINK_12",
            73 => "STAR_BLOCK_LINK_13",
            74 => "STAR_BLOCK_LINK_14",
            75 => "STAR_BLOCK_LINK_15",
            76 => "STAR_BLOCK_LINK_16",
            77 => "STAR_BLOCK_LINK_17",
            78 => "STAR_BLOCK_LINK_18",
            79 => "STAR_BLOCK_LINK_19",
            /*Блок - читайте также*/
            80 => "READ_MORE_BLOCK",

		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => IblockTools::find(Iblock::CONTENT_TYPE,Iblock::OPINIONS)->id(),
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => \Core\Underscore::get($_REQUEST,"debug_limit",30),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/info-block/opinions/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "opinions",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
); ?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>