<?
use Bex\Tools\Iblock\IblockTools;
use App\Iblock;

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Аналитика, экспертные мнения");
$APPLICATION->SetPageProperty('layout', 'bare');
?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"opinions", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "DETAIL_TEXT",
			2 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
        "DETAIL_PROPERTY_CODE" => array(
            /*текстовые блоки (от 1 - т.к. превый (нулевой) текстовый блоке берётся из DETAIL_TEXT)*/
            "TEXT_BLOCK_1",
            "TEXT_BLOCK_2",
            "TEXT_BLOCK_3",
            "TEXT_BLOCK_4",
            "TEXT_BLOCK_5",
            "TEXT_BLOCK_6",
            "TEXT_BLOCK_7",
            "TEXT_BLOCK_8",
            "TEXT_BLOCK_9",
            "TEXT_BLOCK_10",
            "TEXT_BLOCK_11",
            "TEXT_BLOCK_12",
            "TEXT_BLOCK_13",
            "TEXT_BLOCK_14",
            "TEXT_BLOCK_15",
            "TEXT_BLOCK_16",
            "TEXT_BLOCK_17",
            "TEXT_BLOCK_18",
            "TEXT_BLOCK_19",
            "TEXT_BLOCK_20",
            "TEXT_BLOCK_21",
            "TEXT_BLOCK_22",
            "TEXT_BLOCK_23",
            "TEXT_BLOCK_24",
            "TEXT_BLOCK_25",
            "TEXT_BLOCK_26",
            "TEXT_BLOCK_27",
            "TEXT_BLOCK_28",
            "TEXT_BLOCK_29",
            "TEXT_BLOCK_30",
            "TEXT_BLOCK_31",
            "TEXT_BLOCK_32",
            "TEXT_BLOCK_33",
            "TEXT_BLOCK_34",
            "TEXT_BLOCK_35",
            "TEXT_BLOCK_36",
            "TEXT_BLOCK_37",
            "TEXT_BLOCK_38",
            "TEXT_BLOCK_39",
            /*блоки изображений*/
            "IMG_BLOCK_0",
            "IMG_BLOCK_1",
            "IMG_BLOCK_2",
            "IMG_BLOCK_3",
            "IMG_BLOCK_4",
            "IMG_BLOCK_5",
            "IMG_BLOCK_6",
            "IMG_BLOCK_7",
            "IMG_BLOCK_8",
            "IMG_BLOCK_9",
            "IMG_BLOCK_10",
            "IMG_BLOCK_11",
            "IMG_BLOCK_12",
            "IMG_BLOCK_13",
            "IMG_BLOCK_14",
            "IMG_BLOCK_15",
            "IMG_BLOCK_16",
            "IMG_BLOCK_17",
            "IMG_BLOCK_18",
            "IMG_BLOCK_19",
            "IMG_BLOCK_20",
            "IMG_BLOCK_21",
            "IMG_BLOCK_22",
            "IMG_BLOCK_23",
            "IMG_BLOCK_24",
            "IMG_BLOCK_25",
            "IMG_BLOCK_26",
            "IMG_BLOCK_27",
            "IMG_BLOCK_28",
            "IMG_BLOCK_29",
            "IMG_BLOCK_30",
            "IMG_BLOCK_31",
            "IMG_BLOCK_32",
            "IMG_BLOCK_33",
            "IMG_BLOCK_34",
            "IMG_BLOCK_35",
            "IMG_BLOCK_36",
            "IMG_BLOCK_37",
            "IMG_BLOCK_38",
            "IMG_BLOCK_39",
            /*Блок со звездой - описания */
            "STAR_BLOCK_DESCR_0",
            "STAR_BLOCK_DESCR_1",
            "STAR_BLOCK_DESCR_2",
            "STAR_BLOCK_DESCR_3",
            "STAR_BLOCK_DESCR_4",
            "STAR_BLOCK_DESCR_5",
            "STAR_BLOCK_DESCR_6",
            "STAR_BLOCK_DESCR_7",
            "STAR_BLOCK_DESCR_8",
            "STAR_BLOCK_DESCR_9",
            "STAR_BLOCK_DESCR_10",
            "STAR_BLOCK_DESCR_11",
            "STAR_BLOCK_DESCR_12",
            "STAR_BLOCK_DESCR_13",
            "STAR_BLOCK_DESCR_14",
            "STAR_BLOCK_DESCR_15",
            "STAR_BLOCK_DESCR_16",
            "STAR_BLOCK_DESCR_17",
            "STAR_BLOCK_DESCR_18",
            "STAR_BLOCK_DESCR_19",
            "STAR_BLOCK_DESCR_20",
            "STAR_BLOCK_DESCR_21",
            "STAR_BLOCK_DESCR_22",
            "STAR_BLOCK_DESCR_23",
            "STAR_BLOCK_DESCR_24",
            "STAR_BLOCK_DESCR_25",
            "STAR_BLOCK_DESCR_26",
            "STAR_BLOCK_DESCR_27",
            "STAR_BLOCK_DESCR_28",
            "STAR_BLOCK_DESCR_29",
            "STAR_BLOCK_DESCR_30",
            "STAR_BLOCK_DESCR_31",
            "STAR_BLOCK_DESCR_32",
            "STAR_BLOCK_DESCR_33",
            "STAR_BLOCK_DESCR_34",
            "STAR_BLOCK_DESCR_35",
            "STAR_BLOCK_DESCR_36",
            "STAR_BLOCK_DESCR_37",
            "STAR_BLOCK_DESCR_38",
            "STAR_BLOCK_DESCR_39",
            /*Блок со звездой - ссылки */
            "STAR_BLOCK_LINK_0",
            "STAR_BLOCK_LINK_1",
            "STAR_BLOCK_LINK_2",
            "STAR_BLOCK_LINK_3",
            "STAR_BLOCK_LINK_4",
            "STAR_BLOCK_LINK_5",
            "STAR_BLOCK_LINK_6",
            "STAR_BLOCK_LINK_7",
            "STAR_BLOCK_LINK_8",
            "STAR_BLOCK_LINK_9",
            "STAR_BLOCK_LINK_10",
            "STAR_BLOCK_LINK_11",
            "STAR_BLOCK_LINK_12",
            "STAR_BLOCK_LINK_13",
            "STAR_BLOCK_LINK_14",
            "STAR_BLOCK_LINK_15",
            "STAR_BLOCK_LINK_16",
            "STAR_BLOCK_LINK_17",
            "STAR_BLOCK_LINK_18",
            "STAR_BLOCK_LINK_19",
            "STAR_BLOCK_LINK_20",
            "STAR_BLOCK_LINK_21",
            "STAR_BLOCK_LINK_22",
            "STAR_BLOCK_LINK_23",
            "STAR_BLOCK_LINK_24",
            "STAR_BLOCK_LINK_25",
            "STAR_BLOCK_LINK_26",
            "STAR_BLOCK_LINK_27",
            "STAR_BLOCK_LINK_28",
            "STAR_BLOCK_LINK_29",
            "STAR_BLOCK_LINK_30",
            "STAR_BLOCK_LINK_31",
            "STAR_BLOCK_LINK_32",
            "STAR_BLOCK_LINK_33",
            "STAR_BLOCK_LINK_34",
            "STAR_BLOCK_LINK_35",
            "STAR_BLOCK_LINK_36",
            "STAR_BLOCK_LINK_37",
            "STAR_BLOCK_LINK_38",
            "STAR_BLOCK_LINK_39",
            /*Блок - читайте также*/
            "READ_MORE_BLOCK",
        ),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => IblockTools::find(Iblock::CONTENT_TYPE,Iblock::OPINIONS)->id(),
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => \Core\Underscore::get($_REQUEST,"debug_limit",30),
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/info-block/opinions/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "opinions",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
); ?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>